### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by nicrepos** [ShadowFN/LawinServerV3#1]
when i try with reboot or the old era launcher for lawin v2 it doesnt even  connect to the backend it just gives me a error saying that its not up

**Comment by MarvelcoDev** [comment]
> when i try with reboot or the old era launcher for lawin v2 it doesnt even connect to the backend it just gives me a error saying that its not up

It now works i have temp removed the battlepass which caused this dw i will add it back end i fix it
