### ISSUE TITLE
Itemshop

### ISSUE THREAD

**Issue by exprssofficial** [ShadowFN/LawinServerV3#2]
I would like to maybe see a automatic item-shop rotator.

**Comment by MarvelcoDev** [comment]
> Something that can make it a 1:1 fortnite backend is having proper item shops from the version of the build. Like having bundles and all that stuff.

if i have time i will add them

**Comment by AxeOfficial** [comment]
> > Something that can make it a 1:1 fortnite backend is having proper item shops from the version of the build. Like having bundles and all that stuff.
> 
> if i have time i will add them

Also wanted to ask, when are the battlepasses going to work? Cause im tryin to get ch2 s3 battlepass workin.

**Comment by MarvelcoDev** [comment]
> > > Something that can make it a 1:1 fortnite backend is having proper item shops from the version of the build. Like having bundles and all that stuff.
> > 
> > 
> > if i have time i will add them
> 
> Also wanted to ask, when are the battlepasses going to work? Cause im tryin to get ch2 s3 battlepass workin.

soon rn i am working on winter feast , i have finished everything just have to add the mcp endpoint for it

**Comment by AxeOfficial** [comment]
Alr, thank you so much
