### ISSUE TITLE
Itemshop question 

### ISSUE THREAD

**Issue by EFFXCT290** [ShadowFN/LawinServerV3#3]
Is there a way to be for example in season 7 chapter 1 but have skins in the itemshop from chapter 2? 

If it is possible may you add it it would be a great feature

**Comment by MarvelcoDev** [comment]
> Is there a way to be for example in season 7 chapter 1 but have skins in the itemshop from chapter 2?
> 
> If it is possible may you add it it would be a great feature

you would need to have custom paks for that

**Comment by EFFXCT290** [comment]
Where can I find the custom paks?

**Comment by EFFXCT290** [comment]
> > Is there a way to be for example in season 7 chapter 1 but have skins in the itemshop from chapter 2?
> > 
> > If it is possible may you add it it would be a great feature
> 
> you would need to have custom paks for that

Where can I find the custom paks?

**Comment by EFFXCT290** [comment]
> > Is there a way to be for example in season 7 chapter 1 but have skins in the itemshop from chapter 2?
> > 
> > If it is possible may you add it it would be a great feature
> 
> you would need to have custom paks for that

Where can I find the custom paks?
